modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL="https://github.com/itsh1r0/Durability_Tweak/issues"

[[mods]] #mandatory
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL="https://modrinth.com/mod/durability-tweak"
logoFile="assets/durability_tweak/icon.png"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
